version: '2.1'
services:
  api-gateway:
    image: api-gateway
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      GW_AUTH_URL: 'http://localhost:8084/auth/login'
      GW_DOCS_URL: 'http://localhost:3000/api/files'
      GW_PORT: 8080
      GW_UPLOAD_SERVICE: 'upload-service:8080'
      GW_DOWNLOAD_SERVICE: 'download-service:8080'
      GW_FILE_SERVICE: 'file-service:8080'
      GW_PERMISSION_SERVICE: 'permission-service:8080'
      GW_USER_SERVICE: 'user-service:8080'
      GW_SEARCH_SERVICE: 'search-service:8080'
      GW_PERMIT_SERVICE: 'permit-service:8080'
      GW_DELEGATION_SERVICE: 'delegation-service:8080'
      GW_WEB_UI: 'web-ui:8080'
      GW_GOTENBERG_SERVICE: 'http://gotenberg-service:8080'
      GW_ALLOW_ORIGINS: 'http://localhost*'
      GW_SUPPORT_LINK: 'https://open.rocket.chat/home'
      GW_CHROME_DOWNLOAD_URL: 'https://google.com/chrome/'
      GW_APPROVAL_URL: http://localhost/api/v1/request
      GW_VIP_SERVICE: "http://localhost:8094"
      GW_BUCKET_POSTFIX: "kdrive"
      ELASTICSEARCH_URL: 'http://localhost:9200'
      LOG_INDEX: 'kdrive'
      LOG_LEVEL: 'info'
      GW_WHITE_LIST_TEXT: "או להיות מאושר באופן מיוחד"
      ELASTIC_APM_SERVER_URL: 'http://localhost:8200'
      ELASTIC_APM_SERVICE_NAME: 'api-gateway'
      ELASTIC_APM_SERVICE_VERSION: '0.1'
      ELASTIC_APM_ENVIRONMENT: 'development'
      ELASTIC_APM_ACTIVE: 'true'
      ELASTIC_APM_IGNORE_URLS: '/api/healthcheck'
      ELASTIC_APM_CAPTURE_BODY: 'all'
      ELASTIC_APM_METRICS_INTERVAL: '10s'
      GW_EXTERNAL_APM_URL: 'http://localhost:8200'
      GW_SECRET: 'pandora@drive'
    ports:
      - '8080:8080'
    depends_on:
      - upload-service
      - download-service
      - file-service
      - authentication-service
      - permission-service
      - search-service
      - gotenberg-service
  minio:
    image: minio/minio
    volumes:
      - './data:/data'
    ports:
      - '9000:9000'
    environment:
      MINIO_ACCESS_KEY: 'F6WUUG27HBUFSIXVZL59'
      MINIO_SECRET_KEY: 'BPlIUU6SX0ZxiCMo3tIpCMAUdnmkN9Eo9K42NsRR'
    command: server /data
  upload-service:
    image: 'bluehub.azurecr.io/meateam/upload-service:develop'
    environment:
      S3_ACCESS_KEY: 'F6WUUG27HBUFSIXVZL59'
      S3_SECRET_KEY: 'BPlIUU6SX0ZxiCMo3tIpCMAUdnmkN9Eo9K42NsRR'
      S3_ENDPOINT: 'http://minio:9000'
      TCP_PORT: '8080'
      HOST_NAME: 'upload-service'
      ELASTICSEARCH_URL: 'http://localhost:9200'
      LOG_INDEX: 'kdrive'
      LOG_LEVEL: 'debug'
      ELASTIC_APM_SERVER_URL: 'http://localhost:8200'
      ELASTIC_APM_SERVICE_NAME: 'upload-service'
      ELASTIC_APM_SERVICE_VERSION: '0.1'
      ELASTIC_APM_ENVIRONMENT: 'development'
      ELASTIC_APM_ACTIVE: 'true'
      ELASTIC_APM_CAPTURE_BODY: 'all'
      ELASTIC_APM_METRICS_INTERVAL: '10s'
      US_ELASTIC_APM_IGNORE_URLS: '/grpc.health.v1.Health/Check'
    depends_on:
      - minio
    ports:
      - '8081:8080'
  download-service:
    image: 'bluehub.azurecr.io/meateam/download-service:develop'
    environment:
      S3_ACCESS_KEY: 'F6WUUG27HBUFSIXVZL59'
      S3_SECRET_KEY: 'BPlIUU6SX0ZxiCMo3tIpCMAUdnmkN9Eo9K42NsRR'
      S3_ENDPOINT: 'http://minio:9000'
      TCP_PORT: '8080'
      HOST_NAME: 'download-service'
      ELASTICSEARCH_URL: 'http://localhost:9200'
      LOG_INDEX: 'kdrive'
      LOG_LEVEL: 'debug'
      ELASTIC_APM_SERVER_URL: 'http://localhost:8200'
      ELASTIC_APM_SERVICE_NAME: 'download-service'
      ELASTIC_APM_SERVICE_VERSION: '0.1'
      ELASTIC_APM_ENVIRONMENT: 'development'
      ELASTIC_APM_ACTIVE: 'true'
      ELASTIC_APM_CAPTURE_BODY: 'all'
      ELASTIC_APM_METRICS_INTERVAL: '10s'
      DS_ELASTIC_APM_IGNORE_URLS: '/grpc.health.v1.Health/Check'
    ports:
      - '8082:8080'
    depends_on:
      - minio
  file-service:
    image: 'bluehub.azurecr.io/meateam/file-service:develop'
    environment:
      BIND_ADDRESS: '0.0.0.0:8080'
      ELASTICSEARCH_URL: 'http://localhost:9200'
      ELASTICSEARCH_USER: ''
      ELASTICSEARCH_PASSWORD: ''
      LOG_INDEX: 'kdrive'
      APM_SECRET_TOKEN: ''
      FS_APM_SERVICE_NAME: 'file-service'
      ELASTIC_APM_VERIFY_SERVER_CERT: 'false'
      ELASTIC_APM_SERVER_URL: 'http://localhost:8200'
      USER_QUOTA_LIMIT: '10'
      NODE_ENV: 'dev'
      DEBUG_MODE: 'false'
      RECONNECT_ATTEMPTS: '5'
      RECONNECT_TIMEOUT: '2000'
      MONGO_HOST: 'mongodb://mongo:27017/devDB'
    ports:
      - '8083:8080'
    depends_on:
      - mongo
  mongo:
    image: 'mongo:4.0.9'
    ports:
      - '27017:27017'
    volumes:
      - './data/db:/data/db'
    depends_on:
      - minio
  authentication-service:
    image: 'bluehub.azurecr.io/meateam/authentication-service:develop'
    ports:
      - '8084:8080'
    environment:
      SAML_ENTRY_POINT: 'http://localhost:8085/simplesaml/saml2/idp/SSOService.php'
      SAML_ISSUER: 'http://localhost:8084/auth/metadata.xml'
      SAML_CALLBACK_URL: 'http://localhost:8084/auth/metadata.xml/callback'
      USERS_RPC_ENDPOINT: 'user-service:8080'
      SECRET_KEY: 'pandora@drive'
      CLIENT_ENDPOINT: 'http://localhost'
      SHRAGA_URL: 'web-ui:8080'
      STRATEGY: 'shraga'
    depends_on:
      - saml-idp
      - user-service
  saml-idp:
    image: 'bluehub.azurecr.io/meateam/test-saml-idp:latest'
    ports:
      - '8085:8080'
    environment:
      SIMPLESAMLPHP_SP_ENTITY_ID: 'http://localhost:8084/auth/metadata.xml'
      SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE: 'http://localhost:8084/auth/metadata.xml/callback'
      SIMPLESAMLPHP_SP_SINGLE_LOGOUT_SERVICE: 'http://localhost:8084/auth/logout'
  user-service:
    image: 'bluehub.azurecr.io/meateam/user-service:develop'
    ports:
      - '8086:8080'
    environment:
      ELASTIC_APM_SERVER_URL: 'http://localhost:8200'
      ELASTICSEARCH_URL: 'http://localhost:9200'
      KARTOFFEL_URL: 'http://kartoffel-master.eastus.cloudapp.azure.com:3000'
      RPC_PORT: '8080'
      REDIS_PORT: '6379'
      REDIS_HOST: 'redis'
      LOG_INDEX: 'kdrive'
      SPIKE_CLIENT_ID: EPBpjCiczupCXZgBEq3ARZCinUt4LSXtOsVrI1Ub
      SPIKE_CLIENT_SECRET: u5qxEK0sy17ReZ7t8aVeN1gCcdI9hRiM78i9J_9Z6jA2YWcvbgczcchKqZ4WnXOsdT6jxmuVCLC3~RXuVcE5EsOG4JJi~B8AJQSB
      SPIKE_REQUIRED: 'true'
      SPIKE_URL: 'https://spike.westeurope.cloudapp.azure.com'
      SPIKE_AUTH_SERVER_PORT: '1337'
      SPIKE_TOKEN_URL: 'https://spike.westeurope.cloudapp.azure.com:1337/oauth2/token'
      TOKEN: >-
        eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJrYXJ0b2ZmZWwiLCJzdWIiOiI1ZDc2NTA2NTBmYWY2ODIwOTQ4YzMzZGQiLCJzY29wZSI6W10sImNsaWVudElkIjoiRVBCcGpDaWN6dXBDWFpnQkVxM0FSWkNpblV0NExTWHRPc1ZySTFVYiIsImlhdCI6MTU2ODIxMDM1NSwiZXhwIjoxNTY4MjEwNTM1LCJpc3MiOiJodHRwczovLzUxLjE0NC4xNzguMTIxIn0.bSALlqft4U_FiiPr8gtYxx1AOVmnwMxN9-ardt5FhaY_UhKc18PIq5dBSMCMp34sfZnwsBh7uxL3wxDjPxZzYb_RMyLc_wonUurdDjI9zBq5fkyhwdNdBxIirBooVMwjt3mqxVtvVSsWvip3Lfj0zW-qb7n_n5LDRI4YG36cfUc_FCA60keccyHGMJJ1jd8trTvx1XQT8-PTlOlIQifws42Hpc3KIAUM0a2K-VuhK8bdQgcnvkB9Ca55OstOFi27cFf1jV9VO1as5yA6WabDTxht5KxfVN-nMpHhQN0CFw-kngIX2P8F0rlmA2JwmSPVcnDF3OweMAs5CBHQzkdomA
      DEBUG_MODE: 'false'
      USR_MONGO_HOST: 'mongodb://mongo:27017/devDB'
    depends_on:
      - mongo
      - redis
  permission-service:
    image: 'bluehub.azurecr.io/meateam/permission-service:develop'
    ports:
      - '8087:8080'
    environment:
      PS_PORT: '8080'
      PS_MONGO_HOST: 'mongodb://mongo:27017/permission'
      PS_ELASTIC_APM_IGNORE_URLS: '/grpc.health.v1.Health/Check'
      PS_MONGO_CLIENT_CONNECTION_TIMEOUT: '10'
      PS_MONGO_CLIENT_PING_TIMEOUT: '10'
      PS_HEALTH_CHECK_INTERVAL: '3'
      ELASTICSEARCH_URL: 'http://localhost:9200'
      ELASTIC_APM_SERVER_URL: 'http://localhost:8200'
      ELASTIC_APM_ENVIRONMENT: 'development'
      ELASTIC_APM_ACTIVE: 'true'
      ELASTIC_APM_CAPTURE_BODY: 'all'
      ELASTIC_APM_METRICS_INTERVAL: '10s'
    depends_on:
      - mongo
  search-service:
    image: bluehub.azurecr.io/meateam/search-service:develop
    environment:
      SS_PORT: 8080
      SS_HOST_NAME: search-service
      SS_ELASTICSEARCH_URL: http://localhost:9200
      SS_ELASTICSEARCH_INDEX: files
      LOG_INDEX: kdrive
      LOG_LEVEL: debug
      SS_HEALTH_CHECK_INTERVAL: 5
      ELASTIC_APM_SERVER_URL: 'http://localhost:8200'
      ELASTIC_APM_SERVICE_NAME: 'search-service'
      ELASTIC_APM_SERVICE_VERSION: '0.1'
      ELASTIC_APM_ENVIRONMENT: 'development'
      ELASTIC_APM_ACTIVE: 'true'
      ELASTIC_APM_CAPTURE_BODY: 'all'
      ELASTIC_APM_METRICS_INTERVAL: '10s'
      SS_ELASTIC_APM_IGNORE_URLS: '/grpc.health.v1.Health/Check'
    ports:
      - 8088:8080
    depends_on: 
      elasticsearch:
        condition: service_healthy
  gotenberg-service:
    image: bluehub.azurecr.io/meateam/gotenberg:6
    environment:
      DEFAULT_LISTEN_PORT: 8080
      DISABLE_GOOGLE_CHROME: 1
    tmpfs:
      - /tmp
      - /gotenberg/tmp
    ports:
      - 8089:8080
  spike-service:
    image: bluehub.azurecr.io/meateam/spike-service:latest
    environment:
      AUDIENCE: "0mBMe5vYJyuFtvHpEWVDPumqaVl~xr"
      SPIKE_CLIENT_ID: "EPBpjCiczupCXZgBEq3ARZCinUt4LSXtOsVrI1Ub"
      SPIKE_CLIENT_SECRET: "u5qxEK0sy17ReZ7t8aVeN1gCcdI9hRiM78i9J_9Z6jA2YWcvbgczcchKqZ4WnXOsdT6jxmuVCLC3~RXuVcE5EsOG4JJi~B8AJQSB"
      REDIS_URL: 'redis://redis:6379'
      SPIKE_TOKEN_URL: "https://spike.westeurope.cloudapp.azure.com:1337/oauth2/token"
      SPIKE_PUBLIC_KEY_FULL_PATH: "/usr/src/app/utils/publickey.pem"
      SPIKE_PUBKEY_PATH: 'https://spike.westeurope.cloudapp.azure.com:1337/.well-known/publickey.pem'
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    depends_on:
      - redis
    ports:
      - '8090:8080'
  delegation-service:
    image: bluehub.azurecr.io/meateam/delegation-service:develop
    ports:
      - '8091:8080'
    environment:
      DEL_PROT: 8080
      DEL_SPIKE_REQUIRED: 'false'
      PHONE_BOOK_URL: 'http://localhost'
      NODE_TLS_REJECT_UNAUTHORIZED: 0
  permit-service:
    image: bluehub.azurecr.io/meateam/permit-service:develop
    environment:
      PMTS_PORT: 8080
      HOST_NAME: permit-service
      PMTS_MONGO_HOST: mongodb://mongo:27017/permit
      PMTS_GRANT_TYPE: client_credentials
      PMTS_AUDIENCE: "_LCF5avgIpoXSWhY5Jl8mMi0Q~4_~R"
      PMTS_APPROVAL_URL: http://localhost/api/v1/request
      PMTS_SPIKE_SERVICE: spike-service:8080
      PMTS_ELASTIC_APM_IGNORE_URLS: '/grpc.health.v1.Health/Check'
      ELASTICSEARCH_URL: http://localhost:9200
      LOG_INDEX: kdrive
      LOG_LEVEL: debug
      HEALTH_CHECK_INTERVAL: 5
      ELASTIC_APM_SERVER_URL: 'http://localhost:8200'
      ELASTIC_APM_SERVICE_NAME: 'permit-service'
      ELASTIC_APM_SERVICE_VERSION: '0.1'
      ELASTIC_APM_ENVIRONMENT: 'development'
      ELASTIC_APM_ACTIVE: 'true'
      ELASTIC_APM_CAPTURE_BODY: 'all'
      ELASTIC_APM_METRICS_INTERVAL: '10s'
    ports:
      - 8092:8080
    depends_on:
      - mongo
      - spike-service
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    environment: 
      - discovery.type=single-node
    container_name: elasticsearch
    ports: ['9200:9200']
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 5s
      timeout: 10s
      retries: 5
  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.0
    container_name: kibana
    ports: ['5601:5601']
    depends_on: ['elasticsearch']
